### PR TITLE
Fix 192 cljs warnings

### PR DESCRIPTION
**Pull request by w01fe**

### CODE REVIEW

**Comment by loganlinn** [comment]
LGTM

**Comment by talgiat** [comment]
when is this released ?

**Comment by w01fe** [comment]
Not released yet -- would you like me to cut a release?

**Comment by talgiat** [comment]
Yes that will be great

**Comment by w01fe** [comment]
Just released 0.4.1: https://clojars.org/prismatic/schema/versions/0.4.1

**Comment by talgiat** [comment]
Thanks Jason,

Still getting this warnings

```javascript
WARNING: map->Facet at line 22 is being replaced at line 22 src/main/cljs/mex/types.cljs
WARNING: map->DateKeyword at line 63 is being replaced at line 63 src/main/cljs/mex/types.cljs
WARNING: map->DateRange at line 115 is being replaced at line 115 src/main/cljs/mex/types.cljs
WARNING: map->DateYear at line 146 is being replaced at line 146 src/main/cljs/mex/types.cljs
WARNING: map->DateFilter at line 178 is being replaced at line 178 src/main/cljs/mex/types.cljs
WARNING: map->SearchType at line 222 is being replaced at line 222 src/main/cljs/mex/types.cljs
WARNING: map->SearchFilter at line 239 is being replaced at line 239 src/main/cljs/mex/types.cljs
WARNING: map->SearchResult at line 280 is being replaced at line 280 src/main/cljs/mex/types.cljs
WARNING: map->AsyncMsg at line 323 is being replaced at line 323 src/main/cljs/mex/types.cljs
WARNING: map->SyncResult at line 328 is being replaced at line 328 src/main/cljs/mex/types.cljs
WARNING: map->EventMsg at line 333 is being replaced at line 333 src/main/cljs/mex/types.cljs
```

**Comment by w01fe** [comment]
That's a different issue I haven't seen yet, which must be due to an even more recent ClojureScript change (the other issue involved `->X` deftype constructors).   Can you please create a ticket? 

I'm not sure what the right solution is here.  We intentionally overwrite the builtin `map->Record` constructors since they are (or at least were) really slow in Clojure, and the provided versions are much faster.   Do you know if these constructors were recently added in ClojureScript, or the rules for warnings when redefining a function were changed?  

Depending on the answer, and on the relative performance versus the built-in ClojureScript versions, we can potentially define (or conditionally define) these, or perhaps there is a way to redefine a var without triggering the warning?  

Thanks!

**Pull request merged**
