### PR TITLE
Update profile for Clojure 1.8 to RC1

### PR DESCRIPTION
**Pull request by loganlinn**

### CODE REVIEW

**Comment by w01fe** [comment]
:+1:

**Comment by atroche** [comment]
Awesome! When 1.8 is released, are you guys planning to [move to reader conditionals](https://github.com/Prismatic/schema/issues/219) and add [CLJS support for generators and completers](https://github.com/Prismatic/schema/issues/266)?

**Comment by w01fe** [comment]
We'll do this breaking release at some point, but doing them now would only give ~6 months backwards compatibility for Clojure and ~3 months for ClojureScript, which is less than we'd like.  If you want to use completers in cljs now, you can check out the fork  by @estsauver https://github.com/estsauver/schema/blob/master/test/cljx/schema/core_test.cljx#L44

**Comment by atroche** [comment]
Okay, thanks!

On 12 November 2015 at 03:45, Jason Wolfe <notifications@github.com> wrote:

> We'll do this breaking release at some point, but doing them now would
> only give ~6 months backwards compatibility for Clojure and ~3 months for
> ClojureScript, which is less than we'd like. If you want to use completers
> in cljs now, you can check out the fork by @estsauver
> <https://github.com/estsauver>
> https://github.com/estsauver/schema/blob/master/test/cljx/schema/core_test.cljx#L44
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Prismatic/schema/pull/299#issuecomment-155839915>.
>



-- 
-- Alistair

**Pull request merged**
